KEY_CFG_STABLE_APP_URL = "--upgrade-tests-app-catalog-url"
KEY_CFG_STABLE_APP_FILE = "--upgrade-tests-app-file"
KEY_CFG_STABLE_APP_VERSION = "--upgrade-tests-app-version"
KEY_CFG_STABLE_APP_CONFIG = "--upgrade-tests-app-config-file"
KEY_CFG_UPGRADE_HOOK = "--upgrade-tests-upgrade-hook"
KEY_CFG_UPGRADE_SAVE_METADATA = "--upgrade-tests-save-metadata"
