version: 2.1

orbs:
    architect: giantswarm/architect@9.5.5
    codecov: codecov/codecov@6.0.0

workflows:
    test:
        jobs:
            - run-tests:
                  name: run-tests
                  filters:
                      # Needed to trigger job also on git tag.
                      tags:
                          only: /^v.*/

            - architect/push-to-registries:
                  context: architect
                  name: push-to-registries
                  registries-data: |-
                      public gsoci.azurecr.io ACR_GSOCI_USERNAME ACR_GSOCI_PASSWORD true
                  requires:
                      - run-tests
                  filters:
                      # Needed to trigger job also on git tag.
                      tags:
                          only: /^v.*/

                      branches:
                          ignore:
                              - main
                              - master

jobs:
    run-tests:
        machine:
            image: default
        steps:
            - checkout

            - run:
                  name: Execute tests
                  command: |
                      make docker-test-ci

            - codecov/upload
